define(["js/parameters.js"], function(parameters) {
  return {
    apiUrl: parameters[parameters.default_api_url],
    version: "1.6.0",
    mimetypeIconNames: {
      "application/zip": "zip",
      "application/pdf": "pdf",
      "image/tiff": "tiff",
      "application/xml": "xml",
      "application/mods+xml": "mods",
      "application/tei+xml": "tei",
      "text/plain": "txt",
      "image/jpeg": "jpg",
      "text/ocr": "ocr",
      "image/gif": "gif",
      "application/vnd.ms-powerpoint": "ppt",
      "application/msword": "doc",
      "video/quicktime": "qt",
      "application/rtf": "rtf",
      "application/vnd.ms-excel": "xls",
      "unknown": "_blank"
    },
    languageCorrespondance: {
      "unknown": "inconnue",
      "alg": "algonquines, langues",
      "amh": "amharique",
      "ang": "anglo-saxon (ca.450-1100)",
      "ara": "arabe",
      "arc": "araméen d'empire (700-300 BCE)",
      "arm": "arménien",
      "bel": "biélorusse",
      "ber": "berbères, langues",
      "cat": "catalan; valencien",
      "chi": "chinois",
      "cze": "tchèque",
      "dan": "danois",
      "deu": "allemand",
      "dut": "néerlandais; flamand",
      "egy": "égyptien",
      "eng": "anglais",
      "est": "estonien",
      "fin": "finnois",
      "fre": "français",
      "frm": "français moyen (1400-1600)",
      "fro": "français ancien (842-ca.1400)",
      "geo": "géorgien",
      "ger": "allemand",
      "gla": "gaélique; gaélique écossais",
      "gle": "irlandais",
      "glg": "galicien",
      "glv": "manx-mannois",
      "gmh": "allemand, moyen haut (ca. 1050-1500)",
      "got": "gothique",
      "grc": "grec ancien (jusqu'à 1453)",
      "gre": "grec moderne (après 1453)",
      "heb": "hébreu",
      "hin": "hindi",
      "hrv": "croate",
      "hun": "hongrois",
      "ice": "islandais",
      "ind": "indonésien",
      "ira": "iraniennes, langues",
      "ita": "italien",
      "jav": "javanais",
      "jpn": "japonais",
      "kab": "kabyle",
      "kal": "groenlandais",
      "kat": "géorgien",
      "kin": "rwanda",
      "kor": "coréen",
      "kur": "kurde",
      "lat": "latin",
      "lav": "letton",
      "lit": "lituanien",
      "mao": "maori",
      "mas": "massaï",
      "may": "malais",
      "mlg": "malgache",
      "mlt": "maltais",
      "mnc": "mandchou",
      "moh": "mohawk",
      "mon": "mongol",
      "mul": "multilingue",
      "nai": "nord-amérindiennes, langues",
      "nep": "népalais",
      "new": "nepal bhasa; newari",
      "nor": "norvégien",
      "nub": "nubiennes, langues",
      "oci": "occitan (après 1500); provençal",
      "ota": "turc ottoman (1500-1928)",
      "pal": "pahlavi",
      "peo": "perse, vieux (ca. 600-400 av. J.-C.)",
      "per": "persan",
      "phi": "philippines, langues",
      "phn": "phénicien",
      "pol": "polonais",
      "por": "portugais",
      "roa": "romanes, langues",
      "rom": "tsigane",
      "rum": "roumain; moldave",
      "rus": "russe",
      "san": "sanskrit",
      "sco": "écossais",
      "sla": "slaves, langues",
      "slo": "slovaque",
      "slv": "slovène",
      "spa": "espagnol; castillan",
      "sun": "soundanais",
      "swe": "suédois",
      "syr": "syriaque",
      "tah": "tahitien",
      "tib": "tibétain",
      "tuk": "turkmène",
      "tur": "turc",
      "ukr": "ukrainien",
      "und": "indéterminée",
      "uzb": "ouszbek",
      "vie": "vietnamien",
      "wel": "gallois",
      "wln": "wallon",
      "yid": "yiddish",
      "zul": "zoulou",
      "zxx": "pas d'information linguistique"
    },
    flags: ['chi', 'cze', 'deu', 'dut', 'eng', 'fin', 'fre', 'gle', 'gre', 'hun', 'ita', 'jpn', 'per', 'pol', 'por', 'rus', 'sco', 'spa', 'wel']
  };
});